### ISSUE TITLE
[1W1D] Java 주소록 프로젝트 개발 현황

### ISSUE THREAD

**Issue by Youngcircle-kim** [grayashh/2022-develop-study#216]
## 📌 기능 구현 현황

 
- [X] 화면 레이아웃 : 메뉴/세부 메뉴 구현
- [X] 기능 구현 : 연락처 등록(추가)
- [X] 기능 구현 : 연락처 출력
- [ ] 기능 구현 : 순번으로 연락처 삭제-- 진행 중!
- [ ] 기능 구현 : 이름으로 연락처 삭제-- 진행 중!
- [ ] 기능 구현 : 번호로 연락처 삭제-- 진행 중!
- [X] 기능 구현 : 파일 입출력 구현
- [ ] 기능 구현 : 예외 처리
- [X] 기능 구현 : 프로그램 정상 종료

### 메뉴/세부 메뉴 구현
- print_menu 메소드를 구현하여 프로그램을 키면 juso.txt 파일에 있는 내용을 ArrayList에 넣은 후에 print_menu를 실행하기로 함.
### 연락처 등록
- Scanner 클래스를 이용하여 name과 age와 address를 받고 어레이 리스트에 추가한 뒤 파일에 저장하는 형싱으로 코드를 만들었씁니다.
### 연락처 출력
-ArrayList에 있는 값들을 순서대로 출력됨.
### 파일 입출력
-시작할 때 init으로 마지막으로 저장되었는 txt파일의 정보를 불러옴. save() 메소드와 add()메소드다 마지막에 txt 파일을 덮어쓰고 저장하거나 일반적으로 저장하게 만듬.
### 프로그램 종료
- switch 문을 이용해 해당 메뉴 번호를 입력하면 정상적으로 종료되게 메인 메소드를 작성함.

**Comment by grayashh** [comment]
좋습니다~ 삭제 메소드 구현이 어려운데 화이팅입니다
