### ISSUE TITLE
[1W1D] Java 주소록 프로젝트 개발 현황

### ISSUE THREAD

**Issue by jina4066** [grayashh/2022-develop-study#219]
## 📌 기능 구현 현황

 
**- [X] 화면 레이아웃 : 메뉴/세부 메뉴 구현**
**- [X] 기능 구현 : 연락처 등록(추가)**
- [ ] 기능 구현 : 연락처 출력 **-- 진행 중!**
- [ ] 기능 구현 : 순번으로 연락처 삭제
- [ ] 기능 구현 : 이름으로 연락처 삭제
- [ ] 기능 구현 : 번호로 연락처 삭제
- [ ] 기능 구현 : 파일 입출력 구현 **-- 진행 중!**
- [ ] 기능 구현 : 예외 처리
**- [X] 기능 구현 : 프로그램 정상 종료**

## 👩‍💻 주요 개발 내용

: 우선 main 메소드에서 while 문과 switch문을 이용해 종료하기 전까지 메뉴가 출력되도록 구현했습니다. 특히 고민했던 부분은 사용자가 4번을 입력했을 때 빠져나오는 방법이었습니다. 다른 1,2,3번 처럼 단순히 break;로만 빠져나오게 되면 while문안에서 계속 메뉴출력이 이루어지기 때문에, run이라는 불린 타입을 만들어 4번 부분에서 run = false로 선언하여 전체 프로그램을 종료했습니다.

: 또한, 파일 입출력을 위해 txt파일을 읽고 쓸 수 있는 메소드를 각각 만들었습니다. writeTxt 메소드를 생성하여 배열에 있는 정보를 for문을 이용해 한 줄씩 txt 파일에 저장하는 방식으로 구현해봤습니다. get메소드를 이용하여 배열에서 받아왔는데, bufferedwriter에서는 string 타입만 받을 수 있기에 ""로 감싸주어 string 타입으로 변환하여 파일에 작성했습니다. 

: 파일 입출력 부분에서 특히 어렵게 느껴졌던 부분은 사용자의 정보 입력을 받고 배열에 저장한 후, 이 배열 내에서 하나씩 꺼내어 파일에 입력하는 것인지, 아니면 사용자의 입력을 바로 파일로 저장해야 하는 것인지에 대한 고민이었습니다. 우선은 배열에 저장된 정보를 하나씩 꺼내어 파일에 저장하는 방식으로 구현을 해보았습니다. 

: 아직 write 메소드도 완벽하지는 않지만, read 메소드를 살짝 구현해보았는데, 저장된 배열에서 한 줄 씩 꺼내어 출력을 해야 할지, 아니면 split메소드를 이용하여 분리한 후 다른 list에 저장하여 return을 받아야 하는지를 고민하고 있습니다.

**Comment by grayashh** [comment]
수고하셨습니다~
write의 경우 배열 내에서 하나씩 꺼내어 파일에 입력하는 것인지, 아니면 사용자의 입력을 바로 파일로 저장해야 하는 것인지에 대한 부분은 전자의 방법이 옳아보이네요
read을 할 때는 프로그램이 사람이 처음에 입력할 때 처럼 똑같이 작동을 해야된다는 것을 가정하고 txt파일에서 텍스트들을 잘 분리해서 배열에 넣어주는 방식으로 읽어오면 됩니다

**Comment by jina4066** [comment]
감사합니다!

**Comment by jina4066** [comment]
감사합니다!
