### ISSUE TITLE
[1W2D] Java 주소록 프로젝트 개발 현황 (完了)

### ISSUE THREAD

**Issue by Youngcircle-kim** [grayashh/2022-develop-study#221]
## 📌 기능 구현 현황

 
- [x] 화면 레이아웃 : 메뉴/세부 메뉴 구현
- [X] 기능 구현 : 연락처 등록(추가)
- [X] 기능 구현 : 연락처 출력
- [X] 기능 구현 : 순번으로 연락처 삭제
- [X] 기능 구현 : 이름으로 연락처 삭제
- [X] 기능 구현 : 번호로 연락처 삭제
- [X] 기능 구현 : 파일 입출력 구현
- [X] 기능 구현 : 예외 처리
- [X] 기능 구현 : 프로그램 정상 종료

### 삭제 기능
- 인덱스 삭제는 try-catch문을 이용해 예외를 처리했고, int length = sc.nextInt()-1;을 사용해 사용자가 인지하는 순버을 작성함
- 이름 삭제는 리스트를 for문으로 돌리고 동일한 이름이 발견될 경우 그 인덱스 전체를 삭제하는 방향으로 작성함.
- 연락처 삭제도 이름 삭제와 동일한 방법으로 작성함.
### 예외처리
- 메뉴와 세부 메뉴에서 특수기호 및 문자열을 고르는 경우 잘못 된 메뉴라고 다시 돌려보냄.

**Comment by grayashh** [comment]
좋아요 발표 잘 준비해주세요!
