### ISSUE TITLE
[1W2D] Java 주소록 프로젝트 개발 현황

### ISSUE THREAD

**Issue by jina4066** [grayashh/2022-develop-study#224]
## 📌 기능 구현 현황

 
- [X] 화면 레이아웃 : 메뉴/세부 메뉴 구현
- [X] 기능 구현 : 연락처 등록(추가)
- [X] 기능 구현 : 연락처 출력
- [X] 기능 구현 : 순번으로 연락처 삭제
- [ ] 기능 구현 : 이름으로 연락처 삭제
- [ ] 기능 구현 : 번호로 연락처 삭제
- [X] 기능 구현 : 파일 입출력 구현
- [ ] 기능 구현 : 예외 처리
- [X] 기능 구현 : 프로그램 정상 종료

### 주요 개발 내용 
- 상세 개발 내용
: 파일 입출력을 구현하는 write메소드와 read메소드에서 정말 많은 시간을 쏟았는데, 드디어 완성을 하였습니다. 
- write 메소드: 배열에 저장한 값들을 for문을 이용해 한 줄씩 읽어내었는데, 처음에는 get 메소드로 받아와서 배열의 주소값이 출력이 되었습니다. 이를 해결하기 위해 String 타입으로 변환하는 toString 메소드를 사용해야하는지에 대한 고민을 했습니다. 하지만 toString은 배열 자체를 변환해주는 메소드이다 보니, 제가 생각했던 '배열을 한 줄씩 String 타입으로 변환하기'는 어려웠습니다. 그래서 접근자 getter를 이용하여 String 타입의 return 값을 받아와 이를 파일에 입력해주었습니다.
- read 메소드: write 메소드에서 쉼표를 이용해 구분하여 저장해주었기 때문에, 쉼표를 기준으로 분류하여 새 배열에 값을 넣어주었습니다. 
- 프로젝트를 실행한 후, txt 파일을 확인했는데 연락처가 한 줄에 연속적으로 적히는 것을 확인한 후, write메소드의 문자열을 입력한 후, 개행문자를 넣었더니 한 줄씩 차례로 출력되었습니다. 

#command 
예외처리와 각 연락처마다 순서를 매기는 넘버링 기능도 추가해보려고 합니다.

**Comment by grayashh** [comment]
좋습니다~ 파일입출력이 가장 어려운 부분 중 하나인데 잘 구현했네요
인덱스를 재지정하고 넘버링하는 것도 어려운 부분 중 하나인데 화이팅입니다_!
